# Generated by Django 4.2 on 2023-04-16 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Encouragement',
            new_name='Encourage',
        ),
    ]
